# Generated by Django 4.0.5 on 2022-06-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_join_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='joiners',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
