# Generated by Django 4.0.5 on 2022-06-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senders_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
