# Generated by Django 4.0.5 on 2022-06-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_message_senders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
