# Generated by Django 4.0.5 on 2022-06-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
