# Generated by Django 4.0.5 on 2022-06-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_message_senders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='senders_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
