# Generated by Django 4.0.5 on 2022-07-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_message_senders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
